### ISSUE TITLE
Unable to pass arguments to dotnet test when using Coverlet as a global tool

### ISSUE THREAD

**Issue by vkoltachikhin** [Romanx/Cake.Coverlet#36]
Currently Cake.Coverlet doesn't provide a way to pass custom args to dotnet test when Coverlet is installed as a global tool. That makes it impossible to collect coverage and test results in one run (can't add --logger:"trx"). 
May be I'm missing something, correct me if I'm wrong.

**Comment by Romanx** [comment]
Hey there,

The reason for this is that there are a fixed number of settings for the coverlet global tool which we handle. You can find them [here.](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md)

The `--logger:"trx` setting can only be passed to the dotnet test since it's a part of the VS test runner. If you look in the readme you can see how to run dotnet test with coverlet invoked using MSBuild and the cake overloads. 

Hopefully this helps you.
